### ISSUE TITLE
can not make yahoo/mslr successfully

### ISSUE THREAD

**Issue by hby96** [rmit-ir/joint-cascade-ranking#1]
Hi,

when I try to run the command "make -C exp/yahoo",
I get the result as follows: "No rule to make target 'set1.train.txt', needed by 'data'.  Stop."

so how can I solve this problem?

**Comment by lgrz** [comment]
The set1.{train,valid,test}.txt files are part of the Yahoo Learning to Rank Challenge dataset (C14B) and can be found at https://webscope.sandbox.yahoo.com/catalog.php?datatype=c

**Comment by hby96** [comment]
> The set1.{train,valid,test}.txt files are part of the Yahoo Learning to Rank Challenge dataset (C14B) and can be found at https://webscope.sandbox.yahoo.com/catalog.php?datatype=c

thanks for answering!

**Comment by lgrz** [comment]
No problem!
